// Transliterated names of the 114 sūrahs, indexed by chapter number, so a verse
// card can show "Ash-Sharḥ" beside its [94:5] reference like the design. The API
// only returns the numeric ref; this table is static, offline, and tiny.
export const SURAH_NAMES: Record<number, string> = {
  1: "Al-Fātiḥah",
  2: "Al-Baqarah",
  3: "Āl ʿImrān",
  4: "An-Nisāʾ",
  5: "Al-Māʾidah",
  6: "Al-Anʿām",
  7: "Al-Aʿrāf",
  8: "Al-Anfāl",
  9: "At-Tawbah",
  10: "Yūnus",
  11: "Hūd",
  12: "Yūsuf",
  13: "Ar-Raʿd",
  14: "Ibrāhīm",
  15: "Al-Ḥijr",
  16: "An-Naḥl",
  17: "Al-Isrāʾ",
  18: "Al-Kahf",
  19: "Maryam",
  20: "Ṭā Hā",
  21: "Al-Anbiyāʾ",
  22: "Al-Ḥajj",
  23: "Al-Muʾminūn",
  24: "An-Nūr",
  25: "Al-Furqān",
  26: "Ash-Shuʿarāʾ",
  27: "An-Naml",
  28: "Al-Qaṣaṣ",
  29: "Al-ʿAnkabūt",
  30: "Ar-Rūm",
  31: "Luqmān",
  32: "As-Sajdah",
  33: "Al-Aḥzāb",
  34: "Sabaʾ",
  35: "Fāṭir",
  36: "Yā Sīn",
  37: "Aṣ-Ṣāffāt",
  38: "Ṣād",
  39: "Az-Zumar",
  40: "Ghāfir",
  41: "Fuṣṣilat",
  42: "Ash-Shūrā",
  43: "Az-Zukhruf",
  44: "Ad-Dukhān",
  45: "Al-Jāthiyah",
  46: "Al-Aḥqāf",
  47: "Muḥammad",
  48: "Al-Fatḥ",
  49: "Al-Ḥujurāt",
  50: "Qāf",
  51: "Adh-Dhāriyāt",
  52: "Aṭ-Ṭūr",
  53: "An-Najm",
  54: "Al-Qamar",
  55: "Ar-Raḥmān",
  56: "Al-Wāqiʿah",
  57: "Al-Ḥadīd",
  58: "Al-Mujādilah",
  59: "Al-Ḥashr",
  60: "Al-Mumtaḥanah",
  61: "Aṣ-Ṣaff",
  62: "Al-Jumuʿah",
  63: "Al-Munāfiqūn",
  64: "At-Taghābun",
  65: "Aṭ-Ṭalāq",
  66: "At-Taḥrīm",
  67: "Al-Mulk",
  68: "Al-Qalam",
  69: "Al-Ḥāqqah",
  70: "Al-Maʿārij",
  71: "Nūḥ",
  72: "Al-Jinn",
  73: "Al-Muzzammil",
  74: "Al-Muddaththir",
  75: "Al-Qiyāmah",
  76: "Al-Insān",
  77: "Al-Mursalāt",
  78: "An-Nabaʾ",
  79: "An-Nāziʿāt",
  80: "ʿAbasa",
  81: "At-Takwīr",
  82: "Al-Infiṭār",
  83: "Al-Muṭaffifīn",
  84: "Al-Inshiqāq",
  85: "Al-Burūj",
  86: "Aṭ-Ṭāriq",
  87: "Al-Aʿlā",
  88: "Al-Ghāshiyah",
  89: "Al-Fajr",
  90: "Al-Balad",
  91: "Ash-Shams",
  92: "Al-Layl",
  93: "Aḍ-Ḍuḥā",
  94: "Ash-Sharḥ",
  95: "At-Tīn",
  96: "Al-ʿAlaq",
  97: "Al-Qadr",
  98: "Al-Bayyinah",
  99: "Az-Zalzalah",
  100: "Al-ʿĀdiyāt",
  101: "Al-Qāriʿah",
  102: "At-Takāthur",
  103: "Al-ʿAṣr",
  104: "Al-Humazah",
  105: "Al-Fīl",
  106: "Quraysh",
  107: "Al-Māʿūn",
  108: "Al-Kawthar",
  109: "Al-Kāfirūn",
  110: "An-Naṣr",
  111: "Al-Masad",
  112: "Al-Ikhlāṣ",
  113: "Al-Falaq",
  114: "An-Nās",
};

/** Surah name for a "chapter:verse" ref, or "" if the chapter is unknown. */
export function surahName(ref: string): string {
  const chapter = Number(ref.split(":")[0]);
  return SURAH_NAMES[chapter] ?? "";
}
